framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

lexik_jwt_authentication:
    secret_key:       '%env(JWT_SECRET_KEY)%' # required for token creation
    public_key:       '%env(JWT_PUBLIC_KEY)%'  # required for token verification
    pass_phrase:      '%env(JWT_PASSPHRASE)%' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600